name: explorer-deploy-dev

on:
  push:
    branches:
      - "release-dev"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Deploy API server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_A_HOST }}
          port: ${{ secrets.DEV_SERVER_A_PORT }}
          password: ${{ secrets.DEV_SERVER_A_PW }}
          username: ${{ secrets.DEV_SERVER_A_ID }}
          script: |
            pwd
            cd beacon-chain-dev-1
            git fetch --all
            git checkout release-dev
            docker rm -f pdao-pbc-api-server-dev-container
            docker build -t pdao-pbc-api-server-dev -f api-server/Dockerfile .
            docker image prune -f
            docker run -p 4000:4000 --name pdao-pbc-api-server-dev-container -d pdao-pbc-api-server-dev
      - name: Deploy explorer static file server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_A_HOST }}
          port: ${{ secrets.DEV_SERVER_A_PORT }}
          password: ${{ secrets.DEV_SERVER_A_PW }}
          username: ${{ secrets.DEV_SERVER_A_ID }}
          script: |
            pwd
            cd beacon-chain-dev-2
            git fetch --all
            git checkout release-dev
            cd explorer
            docker rm -f pdao-pbc-explorer-dev-container
            docker build -t pdao-pbc-explorer-dev .
            docker image prune -f
            docker run -p 4100:8080 --name pdao-pbc-explorer-dev-container -d pdao-pbc-explorer-dev
