name: explorer-deploy

on:
  push:
    branches:
      - "release-dev"

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_A_HOST }}
          port: ${{ secrets.DEV_SERVER_A_PORT }}
          password: ${{ secrets.DEV_SERVER_A_PW }}
          username: ${{ secrets.DEV_SERVER_A_ID }}
          script: |
            ls
